// Auto-generated by NutBot Widget Creator. Do not edit the marked sections manually.
// CODE only — explicit React.lazy() entries, one per custom widget.
//
// Turbopack requires static import() paths (template literals don't work for
// auto-discovery), so every widget gets an explicit lazy declaration plus a map
// entry. The creator tool appends between the markers on create/import and
// removes the two matching lines on delete. Never hand-edit the marked regions.

import { lazy } from "react";
import type { ComponentType } from "react";

// --- custom-components start ---
const _cube_timer = lazy(() => import("@/components/widgets/custom/cube-timer/CubeTimerWidget").then((m) => ({ default: m.CubeTimerWidget })));
const _glyph_matrix = lazy(() => import("@/components/widgets/custom/glyph-matrix/GlyphMatrixWidget").then((m) => ({ default: m.GlyphMatrixWidget })));
const _quick_links = lazy(() => import("@/components/widgets/custom/quick-links/QuickLinksWidget").then((m) => ({ default: m.QuickLinksWidget })));
const _verlet_sim = lazy(() => import("@/components/widgets/custom/verlet-sim/VerletSimWidget").then((m) => ({ default: m.VerletSimWidget })));
const _world_clock = lazy(() => import("@/components/widgets/custom/world-clock/WorldClockWidget").then((m) => ({ default: m.WorldClockWidget })));
const _spotify_visualizer = lazy(() => import("@/components/widgets/custom/spotify-visualizer/SpotifyVisualizerWidget").then((m) => ({ default: m.SpotifyVisualizerWidget })));
const _weather_updated = lazy(() => import("@/components/widgets/custom/weather-updated/WeatherUpdatedWidget").then((m) => ({ default: m.WeatherUpdatedWidget })));
const _idea_inbox = lazy(() => import("@/components/widgets/custom/idea-inbox/IdeaInboxWidget").then((m) => ({ default: m.IdeaInboxWidget })));
const _claude_usage = lazy(() => import("@/components/widgets/custom/claude-usage/ClaudeUsageWidget").then((m) => ({ default: m.ClaudeUsageWidget })));
// --- custom-components end ---

export const CUSTOM_COMPONENT_MAP: Record<string, ComponentType> = {
// --- custom-map start ---
  "cube-timer": _cube_timer,
  "glyph-matrix": _glyph_matrix,
  "quick-links": _quick_links,
  "verlet-sim": _verlet_sim,
  "world-clock": _world_clock,
  "spotify-visualizer": _spotify_visualizer,
  "weather-updated": _weather_updated,
  "idea-inbox": _idea_inbox,
  "claude-usage": _claude_usage,
// --- custom-map end ---
};
