// Auto-generated by NutBot Widget Creator. Do not edit the generated sections manually.
// The creator tool manages the imports, manifest entries, and order list.
// You may add hand-written widgets here following the same pattern.

import type { WidgetManifest } from "./widgets";

// --- generated imports start ---
import { Thermometer, Dumbbell } from "lucide-react";
import { WeatherWidget } from "@/components/widgets/custom/weather/WeatherWidget";
import { GymWidget } from "@/components/widgets/custom/gym/GymWidget";
import { Timer } from "lucide-react";
import { CubeWidget } from "@/components/widgets/custom/cube/CubeWidget";
import { MessageSquare } from "lucide-react";
import { WhatsAppWidget } from "@/components/widgets/custom/whatsapp/WhatsAppWidget";
// --- generated imports end ---

export const CUSTOM_WIDGETS: Record<string, WidgetManifest> = {
  // --- generated widgets start ---
  weather: {
    id: "weather",
    title: "weather",
    icon: Thermometer,
    component: WeatherWidget,
    sizes: ["S", "M", "L"],
    orientations: ["h"],
    defaults: { size: "M", orientation: "h" },
    settings: [
      {
        key: "city",
        label: "city",
        type: "text",
        default: "",
        placeholder: "auto-detect (leave blank)",
      },
      {
        key: "units",
        label: "units",
        type: "select",
        default: "f",
        options: [
          { value: "f", label: "°F" },
          { value: "c", label: "°C" },
        ],
      },
    ],
  },
  gym: {
    id: "gym",
    title: "gym",
    icon: Dumbbell,
    component: GymWidget,
    sizes: ["S", "M", "L"],
    orientations: ["h"],
    defaults: { size: "M", orientation: "h" },
  },
  cube: {
    id: "cube",
    title: "cube timer",
    icon: Timer,
    component: CubeWidget,
    sizes: ["S", "M", "L"],
    orientations: ["h"],
    defaults: { size: "M", orientation: "h" },
  },
  whatsapp: {
    id: "whatsapp",
    title: "whatsapp",
    icon: MessageSquare,
    component: WhatsAppWidget,
    sizes: ["S", "M", "L"],
    orientations: ["h"],
    defaults: { size: "M", orientation: "h" },
    settings: [
      {
        key: "groupId",
        label: "group JID",
        type: "text",
        default: "",
        placeholder: "override WHATSAPP_GROUP_ID (optional)",
      },
    ],
  },
  // --- generated widgets end ---
};

export const CUSTOM_DEFAULT_ORDER: string[] = [
  // --- generated order start ---
  "weather",
  "gym",
  "cube",
  "whatsapp",
  // --- generated order end ---
];
