// Auto-generated by NutBot Widget Creator. Do not edit the generated sections manually.
// The creator tool manages the imports, manifest entries, and order list.
// You may add hand-written widgets here following the same pattern.

import type { WidgetManifest } from "./widgets";

// --- generated imports start ---
import { Thermometer } from "lucide-react";
import { WeatherWidget } from "@/components/widgets/custom/weather/WeatherWidget";
// --- generated imports end ---

export const CUSTOM_WIDGETS: Record<string, WidgetManifest> = {
  // --- generated widgets start ---
  weather: {
    id: "weather",
    title: "weather",
    icon: Thermometer,
    component: WeatherWidget,
    sizes: ["S", "M", "L"],
    orientations: ["h"],
    defaults: { size: "M", orientation: "h" },
    settings: [
      {
        key: "city",
        label: "city",
        type: "text",
        default: "",
        placeholder: "auto-detect (leave blank)",
      },
      {
        key: "units",
        label: "units",
        type: "select",
        default: "f",
        options: [
          { value: "f", label: "°F" },
          { value: "c", label: "°C" },
        ],
      },
    ],
  },
  // --- generated widgets end ---
};

export const CUSTOM_DEFAULT_ORDER: string[] = [
  // --- generated order start ---
  "weather",
  // --- generated order end ---
];
