// Auto-generated by NutBot Widget Creator. Do not edit the marked sections manually.
// CODE only — explicit React.lazy() entries, one per custom widget.
//
// Turbopack requires static import() paths (template literals don't work for
// auto-discovery), so every widget gets an explicit lazy declaration plus a map
// entry. The creator tool appends between the markers on create/import and
// removes the two matching lines on delete. Never hand-edit the marked regions.

import { lazy } from "react";
import type { ComponentType } from "react";

// --- custom-components start ---
const _weather = lazy(() => import("@/components/widgets/custom/weather/WeatherWidget").then((m) => ({ default: m.WeatherWidget })));
const _slideshow = lazy(() => import("@/components/widgets/custom/slideshow/SlideshowWidget").then((m) => ({ default: m.SlideshowWidget })));
// --- custom-components end ---

export const CUSTOM_COMPONENT_MAP: Record<string, ComponentType> = {
// --- custom-map start ---
  weather: _weather,
  "slideshow": _slideshow,
// --- custom-map end ---
};
